feat :  친구요청 전송 두 번 누르면 경고 모달 창 띄우기
GunGonGamLee/ft_transcendence pull request #405
Opened 2024-03-06 08:21 UTC by bluedog129

**************************************************************************************
## ✅ 풀\_리퀘스트 체크리스트

- [x] PR 제목: [feat/fix/refactor...] 작업 내용 한 줄 요약 (브랜치 이름) #이슈번호
- [x] commit message 가 적절한지 확인해주세요.
- [x] 적절한 branch 로 요청했는지 확인해주세요.
- [x] Assignees, Label 을 붙여주세요.
- [x] 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer 로 등록해주세요.
- [x] PR이 승인된 경우 해당 브랜치는 삭제해 주세요!

## 🔄 변경 사항

무엇을 합니다!
- 전송을 두 번 이상 누르는 것을 방지하기 위한 경고창 생성
- 모달창의 위치에 대한 설정을 뷰포트로 변경

## 📎 변경한 이유
- 전송을 두 번 이상 누르는 것을 방지하기 위한 경고창이 필요했습니다.
- 클러스터 아이맥 환경에서도 동일한 위치를 제공하기 위해서 모달창의 위치 설정을 뷰포트로 변경했습니다.

closes: #400

## 👨🏻‍💻 테스트 체크리스트

- 전송 버튼 두 번 이상 누름
- 브라우저 창을 열씸히 늘였다 줄여봄

https://github.com/GunGonGamLee/ft_transcendence/assets/50707297/c05b4065-812c-4423-8e7c-c0c3bacc2b56

**************************************************************************************

2024-03-06 08:38 UTC, donghyun1998 approved these changes

2024-03-06 08:38 UTC, donghyun1998 commented
버튼 두번 누를때 모달띄우기 확인했습니다!

2024-03-06 08:45 UTC, nyj001012 requested changes

2024-03-06 08:45 UTC, nyj001012 commented on frontend/src/header/mainHeader/header.js
> +        <img id="warning-modal-close" alt="setting" style="position: absolute; width: 70px; height: 70px; left: 770px; top: 26px;" src="../../../assets/images/close.png" />
`<div id="warning-modal-wrapper">`의 width와 height를 px로 준 건 그렇다 쳐도, 이미 보냈다의 안내문의 위치를 지정하실 때 `left: 120px; top: 80px;`로 주시면 아이맥 갔을 때 무조건 위치 틀어집니다.

`<img id="warning-modal-close">`는 닫기 버튼 같은데, 이 엘리먼트도 마찬가지로 `left:770px; top: 26px;`처럼 속성값 주시면 위와 같은 현상 벌어질거예요. 자칫하면 wrapper 바깥에 해당 버튼이 위치할 수도 있습니다.

2024-03-07 03:51 UTC, bluedog129 commented on frontend/src/header/mainHeader/header.js
> +        <img id="warning-modal-close" alt="setting" style="position: absolute; width: 70px; height: 70px; left: 770px; top: 26px;" src="../../../assets/images/close.png" />
넵 수정하겠습니다!

2024-03-08 06:13 UTC, bluedog129 commented on frontend/src/header/mainHeader/header.js
> +        <img id="warning-modal-close" alt="setting" style="position: absolute; width: 70px; height: 70px; left: 770px; top: 26px;" src="../../../assets/images/close.png" />
수정 했습니다!

2024-03-08 06:25 UTC, nyj001012 approved these changes
단위 변경 사항 확인했습니다.

2024-03-08 06:26 UTC, merged